package rules.test.lof.alone

import com.czdx.parkingcharge.domain.pr.ParkingRecord
import com.czdx.parkingcharge.utils.ParkingFeeUtil
import java.math.BigDecimal

// 算费不包含免费时间处理，需要扣减掉免费停车时间
rule "AN111NCFT-hide-ncft"
    activation-group "charge-rule"
    salience 110
    when
        $pRecord:ParkingRecord(useFreeTime)
    then
        // 扣减免费时间
        BigDecimal fee = ParkingFeeUtil.substractFreeTime($pRecord, 18, null);
        $pRecord.setParkingFee(fee);
end

// 超过时长后，隐藏的分割，不会考虑免费时长次数、首时段计费方式
rule "AN111NCFT-hide-1"
    activation-group "charge-rule"
    salience 110
    when
        $pRecord:ParkingRecord($duration: parkingDuration > 1440)
    then
        // 该分割，不允许使用免费时长、首时段
        BigDecimal fee = ParkingFeeUtil.divideHideDuration2ChargeFee($pRecord, 1440, null);
        $pRecord.setParkingFee(fee);
end

// 一个期间，时长1440分钟，5元每60分钟
rule "AN111NCFT-2"
    activation-group "charge-rule"
    salience 90
    when
        $pRecord:ParkingRecord($duration: parkingDuration > 0)
    then
        System.out.println("触发规则：AN111NCFT-2");
        BigDecimal fee = ParkingFeeUtil.chargeParkingFee($duration, 60, BigDecimal.valueOf(4),
        "1", BigDecimal.valueOf(100));
        $pRecord.setParkingFee(fee);
end
