package rules.parking
import com.czdx.parkingcharge.domain.pr.ParkingRecord
import com.czdx.parkingcharge.utils.ParkingFeeUtil
import java.math.BigDecimal


// 超出最高限价时间
rule "STMY111-divide-maxcharge"
    activation-group "charge-rule"
    salience 200
    when
        $pRecord:ParkingRecord($duration: parkingDuration >= 1440)
    then
        System.out.println("触发规则：超出最高限价时间分割");
        BigDecimal fee = ParkingFeeUtil.divideCP2ChargeFee($pRecord, 1440, BigDecimal.valueOf(50), "1", "1");
        $pRecord.setParkingFee(fee);
end


// 按时刻期间分割计费
rule "STMY111-divide-starttime"
    activation-group "charge-rule"
    salience 180
    when
        $pRecord:ParkingRecord(needMTDivide)
    then
        System.out.println("触发规则：需要进行时刻分割");
        BigDecimal fee = ParkingFeeUtil.divideTime2ChargeFee($pRecord, BigDecimal.valueOf(50), "1", "1", "00:00", "08:00", "16:00");
        $pRecord.setParkingFee(fee);
end


// 一个期间，时长1440分钟，5元每60分钟
rule "STMY111_I-1"
    activation-group "charge-rule"
    salience 90
    when
        $pRecord:ParkingRecord($duration: parkingDuration > 0)
    then
        System.out.println("触发规则：STMY111-I-1");
        long remainingMins = $duration;
        BigDecimal fee = ParkingFeeUtil.chargeParkingFee(remainingMins, 60, BigDecimal.valueOf(1), "1", BigDecimal.valueOf(50));
        $pRecord.setParkingFee(fee);
end

// 一个期间，时长1440分钟，5元每60分钟
rule "STMY111_II-1"
    activation-group "charge-rule"
    salience 90
    when
        $pRecord:ParkingRecord($duration: parkingDuration > 0)
    then
        System.out.println("触发规则：STMY111-I-1");
        long remainingMins = $duration;
        BigDecimal fee = ParkingFeeUtil.chargeParkingFee(remainingMins, 60, BigDecimal.valueOf(2), "1", BigDecimal.valueOf(50));
        $pRecord.setParkingFee(fee);
end

// 一个期间，时长1440分钟，5元每60分钟
rule "STMY111_III-1"
    activation-group "charge-rule"
    salience 90
    when
        $pRecord:ParkingRecord($duration: parkingDuration > 0)
    then
        System.out.println("触发规则：STMY111-I-1");
        long remainingMins = $duration;
        BigDecimal fee = ParkingFeeUtil.chargeParkingFee(remainingMins, 60, BigDecimal.valueOf(3), "1", BigDecimal.valueOf(50));
        $pRecord.setParkingFee(fee);
end



