package rules.parking
import com.czdx.parkingcharge.domain.pr.ParkingRecord
import com.czdx.parkingcharge.utils.ParkingFeeUtil
import java.math.BigDecimal

rule "PARKING_CHARGE_P20230222150046_56_CP_999"
    activation-group "charge-rule"
    salience 999
    when
        $pRecord:ParkingRecord($duration: parkingDuration >= 1440)
    then
        System.out.println("触发规则：PARKING_CHARGE_P20230222150046_56_CP_999");
            BigDecimal fee = ParkingFeeUtil.divideCP2ChargeFee($pRecord, 1440, BigDecimal.valueOf(20), "1", "1");
    $pRecord.setParkingFee(fee);
end

rule "PARKING_CHARGE_P20230222150046_56_TD_666"
    activation-group "charge-rule"
    salience 666
    when
        $pRecord:ParkingRecord(needMTDivide)
    then
        System.out.println("触发规则：PARKING_CHARGE_P20230222150046_56_TD_666");
        BigDecimal fee = ParkingFeeUtil.divideTime2ChargeFee($pRecord, BigDecimal.valueOf(20.00), "1", "1", "09:00", "21:00");
        $pRecord.setParkingFee(fee);
end

rule "PARKING_CHARGE_P20230222150046_56_IHD_444"
    activation-group "charge-rule"
    salience 444
    when
        $pRecord:ParkingRecord($duration: parkingDuration > 720, useFirstPeriod)
    then
        System.out.println("触发规则：PARKING_CHARGE_P20230222150046_56_IHD_444");
        BigDecimal fee = ParkingFeeUtil.divideHideDuration2ChargeFee($pRecord, 720, BigDecimal.valueOf(20));
        $pRecord.setUseFirstPeriod(false);
        $pRecord.setParkingFee(fee);
end

rule "PARKING_CHARGE_P20230222150046_56_IHD_443"
    activation-group "charge-rule"
    salience 443
    when
        $pRecord:ParkingRecord($duration: parkingDuration > 660, !useFirstPeriod)
    then
        System.out.println("触发规则：PARKING_CHARGE_P20230222150046_56_IHD_443");
        BigDecimal fee = ParkingFeeUtil.divideHideDuration2ChargeFee($pRecord, 660, BigDecimal.valueOf(20));
        $pRecord.setParkingFee(fee);
end

rule "PARKING_CHARGE_P20230222150046_56_I_0"
    activation-group "charge-rule"
    salience 0
    when
        $pRecord:ParkingRecord(    $duration: parkingDuration <= 18, useFreeTime)
    then
        System.out.println("触发规则：PARKING_CHARGE_P20230222150046_56_I_0");
            $pRecord.setParkingFee(BigDecimal.ZERO);
end

rule "PARKING_CHARGE_P20230222150046_56_I_1"
    activation-group "charge-rule"
    salience 0
    when
        $pRecord:ParkingRecord($duration: parkingDuration > 0, parkingDuration <= 60, useFirstPeriod)
    then
        System.out.println("触发规则：PARKING_CHARGE_P20230222150046_56_I_1");
        BigDecimal fee = ParkingFeeUtil.chargeParkingFee($duration - 0, 60, BigDecimal.valueOf(1), "1", BigDecimal.valueOf(0), BigDecimal.valueOf(0));
        $pRecord.setUseFirstPeriod(false);
        $pRecord.setParkingFee(fee);
end

rule "PARKING_CHARGE_P20230222150046_56_I_2"
    activation-group "charge-rule"
    salience 0
    when
        $pRecord:ParkingRecord($duration: parkingDuration > 60, parkingDuration <= 180, useFirstPeriod)
    then
        System.out.println("触发规则：PARKING_CHARGE_P20230222150046_56_I_2");
        BigDecimal fee = ParkingFeeUtil.chargeParkingFee($duration - 60, 60, BigDecimal.valueOf(2), "1", BigDecimal.valueOf(0), BigDecimal.valueOf(1));
        $pRecord.setUseFirstPeriod(false);
        $pRecord.setParkingFee(fee);
end

rule "PARKING_CHARGE_P20230222150046_56_I_3"
    activation-group "charge-rule"
    salience 0
    when
        $pRecord:ParkingRecord($duration: parkingDuration > 0, parkingDuration <= 120)
    then
        System.out.println("触发规则：PARKING_CHARGE_P20230222150046_56_I_3");
        BigDecimal fee = ParkingFeeUtil.chargeParkingFee($duration - 0, 60, BigDecimal.valueOf(2), "1", BigDecimal.valueOf(0), BigDecimal.valueOf(0));
        $pRecord.setParkingFee(fee);
end

rule "PARKING_CHARGE_P20230222150046_56_I_4"
    activation-group "charge-rule"
    salience 0
    when
        $pRecord:ParkingRecord($duration: parkingDuration > 180, useFirstPeriod)
    then
        System.out.println("触发规则：PARKING_CHARGE_P20230222150046_56_I_4");
        BigDecimal fee = ParkingFeeUtil.chargeParkingFee($duration - 180, 60, BigDecimal.valueOf(3), "1", BigDecimal.valueOf(0), BigDecimal.valueOf(5));
        $pRecord.setUseFirstPeriod(false);
        $pRecord.setParkingFee(fee);
end

rule "PARKING_CHARGE_P20230222150046_56_I_5"
    activation-group "charge-rule"
    salience 0
    when
        $pRecord:ParkingRecord($duration: parkingDuration > 120)
    then
        System.out.println("触发规则：PARKING_CHARGE_P20230222150046_56_I_5");
        BigDecimal fee = ParkingFeeUtil.chargeParkingFee($duration - 120, 60, BigDecimal.valueOf(3), "1", BigDecimal.valueOf(0), BigDecimal.valueOf(4));
        $pRecord.setParkingFee(fee);
end

rule "PARKING_CHARGE_P20230222150046_56_IIHD_444"
    activation-group "charge-rule"
    salience 444
    when
        $pRecord:ParkingRecord($duration: parkingDuration > 720, useFirstPeriod)
    then
        System.out.println("触发规则：PARKING_CHARGE_P20230222150046_56_IIHD_444");
        BigDecimal fee = ParkingFeeUtil.divideHideDuration2ChargeFee($pRecord, 720, BigDecimal.valueOf(20));
        $pRecord.setUseFirstPeriod(false);
        $pRecord.setParkingFee(fee);
end

rule "PARKING_CHARGE_P20230222150046_56_IIHD_443"
    activation-group "charge-rule"
    salience 443
    when
        $pRecord:ParkingRecord($duration: parkingDuration > 660, !useFirstPeriod)
    then
        System.out.println("触发规则：PARKING_CHARGE_P20230222150046_56_IIHD_443");
        BigDecimal fee = ParkingFeeUtil.divideHideDuration2ChargeFee($pRecord, 660, BigDecimal.valueOf(20));
        $pRecord.setParkingFee(fee);
end

rule "PARKING_CHARGE_P20230222150046_56_II_0"
    activation-group "charge-rule"
    salience 0
    when
        $pRecord:ParkingRecord(    $duration: parkingDuration <= 18, useFreeTime)
    then
        System.out.println("触发规则：PARKING_CHARGE_P20230222150046_56_II_0");
            $pRecord.setParkingFee(BigDecimal.ZERO);
end

rule "PARKING_CHARGE_P20230222150046_56_II_1"
    activation-group "charge-rule"
    salience 0
    when
        $pRecord:ParkingRecord($duration: parkingDuration > 0, parkingDuration <= 60, useFirstPeriod)
    then
        System.out.println("触发规则：PARKING_CHARGE_P20230222150046_56_II_1");
        BigDecimal fee = ParkingFeeUtil.chargeParkingFee($duration - 0, 60, BigDecimal.valueOf(1), "1", BigDecimal.valueOf(0), BigDecimal.valueOf(0));
        $pRecord.setUseFirstPeriod(false);
        $pRecord.setParkingFee(fee);
end

rule "PARKING_CHARGE_P20230222150046_56_II_2"
    activation-group "charge-rule"
    salience 0
    when
        $pRecord:ParkingRecord($duration: parkingDuration > 60, parkingDuration <= 180, useFirstPeriod)
    then
        System.out.println("触发规则：PARKING_CHARGE_P20230222150046_56_II_2");
        BigDecimal fee = ParkingFeeUtil.chargeParkingFee($duration - 60, 60, BigDecimal.valueOf(2), "1", BigDecimal.valueOf(0), BigDecimal.valueOf(1));
        $pRecord.setUseFirstPeriod(false);
        $pRecord.setParkingFee(fee);
end

rule "PARKING_CHARGE_P20230222150046_56_II_3"
    activation-group "charge-rule"
    salience 0
    when
        $pRecord:ParkingRecord($duration: parkingDuration > 0, parkingDuration <= 120)
    then
        System.out.println("触发规则：PARKING_CHARGE_P20230222150046_56_II_3");
        BigDecimal fee = ParkingFeeUtil.chargeParkingFee($duration - 0, 60, BigDecimal.valueOf(2), "1", BigDecimal.valueOf(0), BigDecimal.valueOf(0));
        $pRecord.setParkingFee(fee);
end

rule "PARKING_CHARGE_P20230222150046_56_II_4"
    activation-group "charge-rule"
    salience 0
    when
        $pRecord:ParkingRecord($duration: parkingDuration > 180, useFirstPeriod)
    then
        System.out.println("触发规则：PARKING_CHARGE_P20230222150046_56_II_4");
        BigDecimal fee = ParkingFeeUtil.chargeParkingFee($duration - 180, 60, BigDecimal.valueOf(3), "1", BigDecimal.valueOf(0), BigDecimal.valueOf(5));
        $pRecord.setUseFirstPeriod(false);
        $pRecord.setParkingFee(fee);
end

rule "PARKING_CHARGE_P20230222150046_56_II_5"
    activation-group "charge-rule"
    salience 0
    when
        $pRecord:ParkingRecord($duration: parkingDuration > 120)
    then
        System.out.println("触发规则：PARKING_CHARGE_P20230222150046_56_II_5");
        BigDecimal fee = ParkingFeeUtil.chargeParkingFee($duration - 120, 60, BigDecimal.valueOf(3), "1", BigDecimal.valueOf(0), BigDecimal.valueOf(4));
        $pRecord.setParkingFee(fee);
end
