package rules.test.lof.alone

import com.czdx.parkingcharge.domain.pr.ParkingRecord
import com.czdx.parkingcharge.utils.ParkingFeeUtil
import java.math.BigDecimal

// 超过时长后，隐藏的分割，不会考虑免费时长次数、首时段计费方式
rule "MN111-hide-1"
    activation-group "charge-rule"
    salience 110
    when
        $pRecord:ParkingRecord($duration: parkingDuration > 120)
    then
        // 该分割，不允许使用免费时长、首时段
        BigDecimal fee = ParkingFeeUtil.divideHideDuration2ChargeFee($pRecord, 120, "Y", null);
        $pRecord.setParkingFee(fee);
end

// 免费时间段 18 分钟
rule "MN111-1"
    activation-group "charge-rule"
    salience 100
    when
        $pRecord:ParkingRecord($duration: parkingDuration <= 18, useFreeTime)
    then
        System.out.println("触发规则：MN111-1");
        $pRecord.setParkingFee(BigDecimal.ZERO);
end

// 首时段，时长30分钟，5元每30分钟
rule "MN111-2"
    activation-group "charge-rule"
    salience 90
    when
        $pRecord:ParkingRecord($duration: parkingDuration > 0, parkingDuration <= 30, useFirstPeriod)
    then
        System.out.println("触发规则：MN111-2");
        long remainingMins = $duration;
        BigDecimal fee = ParkingFeeUtil.chargeParkingFee(remainingMins, 30, BigDecimal.valueOf(5), "1", BigDecimal.valueOf(50));
        $pRecord.setParkingFee(fee);
end

// 第二时段，时长30分钟，4元每30分钟
rule "MN111-3"
    activation-group "charge-rule"
    salience 90
    when
        $pRecord:ParkingRecord($duration: parkingDuration > 30, parkingDuration <= 60, useFirstPeriod)
    then
        System.out.println("触发规则：MN111-3");
        long remainingMins = $duration - 30;
        BigDecimal fee = ParkingFeeUtil.chargeParkingFee(remainingMins, 30, BigDecimal.valueOf(4), "1", BigDecimal.valueOf(25));
        $pRecord.setParkingFee(fee);
end

// 第三时段，时长60分钟，3元每60分钟
rule "MN111-4"
    activation-group "charge-rule"
    salience 90
    when
        $pRecord:ParkingRecord($duration: parkingDuration > 0)
    then
        System.out.println("触发规则：MN111-4");
        long remainingMins = $duration;
        BigDecimal fee = ParkingFeeUtil.chargeParkingFee(remainingMins, 60, BigDecimal.valueOf(3), "1", BigDecimal.valueOf(25));
        $pRecord.setParkingFee(fee);
end
